name: Rust

on:
  release:
    types:
      - created

jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    - name: Install rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Build the executable
      run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

    - name: Tar x86_64 binary
      run: tar -czvf token-gen-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release token-gen

    - name: Zip windows binary
      run: zip -j token-gen-windows.zip target/x86_64-pc-windows-gnu/release/token-gen.exe

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 token-gen-gnu-linux-x86_64.tar.gz > token-gen-gnu-linux-x86_64.tar.gz.sha256
        shasum -a 256 token-gen-windows.zip > token-gen-windows.zip.sha256

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["token-gen-gnu-linux-x86_64.tar.gz", "token-gen-windows.zip", "token-gen-gnu-linux-x86_64.tar.gz.sha256", "token-gen-windows.zip.sha256"]'
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install rustup targets
      run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

    - name: Build the executable
      run: cargo build --release --target x86_64-apple-darwin --target aarch64-apple-darwin

    - name: Zip x86_64 binary
      run: zip -j token-gen-darwin-x86_64.zip target/x86_64-apple-darwin/release token-gen


    - name: Zip x86_64 binary
      run: zip -j token-gen-darwin-aarch64.zip target/aarch64-apple-darwin/release token-gen

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 token-gen-darwin-x86_64.tar.gz > token-gen-darwin-x86_64.tar.gz.sha256
        shasum -a 256 token-gen-darwin-aarch64.zip > token-gen-darwin-aarch64.zip.sha256

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["token-gen-darwin-x86_64.tar.gz", "token-gen-darwin-aarch64.zip", "token-gen-darwin-x86_64.zip.sha256", "token-gen-aarch64-darwin.zip.sha256"]'
